name: Continuous Integration - Weekly

on:
  schedule:
    # Checks out main by default.
    - cron: '0 0 * * 0'
  # FIXME - for PR testing only, remove before merge
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:
  notebooks-stable:
    name: All Notebooks Isolated Test against Cirq stable
    env:
      NOTEBOOK_PARTITIONS: 4
    strategy:
      matrix:
        # partitions should be named partition-0 to partition-(NOTEBOOK_PARTITIONS-1)
        partition: [partition-0, partition-1, partition-2, partition-3]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r dev_tools/requirements/isolated-base.env.txt
      - name: Notebook tests
        run: check/pytest -n auto -m weekly dev_tools/notebooks/isolated_notebook_test.py -k ${{matrix.partition}}
      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        if: failure()
        with:
          name: notebook-outputs
          path: out
