name: Continuous Integration - Weekly

on:
  schedule:
    # Checks out main by default.
    - cron: '0 0 * * 0'

  # Allow manual invocation.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:
  notebooks-stable:
    if: github.repository_owner == 'quantumlib'
    name: All Notebooks Isolated Test against Cirq stable
    env:
      NOTEBOOK_PARTITIONS: 4
    strategy:
      matrix:
        # partitions should be named partition-0 to partition-(NOTEBOOK_PARTITIONS-1)
        partition: [partition-0, partition-1, partition-2, partition-3]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r dev_tools/requirements/isolated-base.env.txt
      - name: Notebook tests
        run: check/pytest -n auto -m weekly dev_tools/notebooks/isolated_notebook_test.py -k ${{matrix.partition}}
      - name: Persist the outputs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: failure()
        with:
          name: notebook-outputs
          path: out
