name: Continuous Integration - Weekly

on:
  schedule:
    # Checks out main by default.
    - cron: '0 0 * * 0'

  # Allow manual invocation.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# Declare default permissions as read only.
permissions: read-all

jobs:
  notebooks-stable:
    if: github.repository_owner == 'quantumlib'
    name: All Notebooks Isolated Test against Cirq stable
    env:
      NOTEBOOK_PARTITIONS: 4
    strategy:
      matrix:
        # partitions should be named partition-0 to partition-(NOTEBOOK_PARTITIONS-1)
        partition: [partition-0, partition-1, partition-2, partition-3]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r dev_tools/requirements/isolated-base.env.txt
      - name: Notebook tests
        run: check/pytest -n auto -m weekly dev_tools/notebooks/isolated_notebook_test.py -k ${{matrix.partition}}
      - name: Persist the outputs
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: failure()
        with:
          name: notebook-outputs
          path: out
