name: Continuous Integration

on: [pull_request]

jobs:
  quick_test:
    name: Misc check
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Misc
        run: check/misc
  format:
    name: Format check
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install black
        run: cat dev_tools/conf/pip-list-dev-tools.txt | grep black | xargs pip install
      - name: Format
        run: check/format-incremental
  mypy:
    name: Type check
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install mypy
        run: cat dev_tools/conf/pip-list-dev-tools.txt | grep mypy | xargs pip install
      - name: Type check
        run: check/mypy
  changed_files:
    name: Changed files test
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install changed files test dependencies
        run: dev_tools/conf/pip-install-minimal-for-pytest-changed-files.sh
      - name: Changed files test
        run: check/pytest-changed-files
  lint:
    name: Lint check
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install pylint
        run: cat dev_tools/conf/pip-list-dev-tools.txt | grep "pylint" | grep -v "#" | xargs pip install
      - name: Lint
        run: check/pylint
  doc_test:
    name: Doc test
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          python -m pip install -r cirq/contrib/contrib-requirements.txt
          pip install -r dev_tools/conf/pip-list-dev-tools.txt
      - name: RST check
        run: find . -type f -name "*.rst" | xargs rstcheck --report warning --ignore-directives autoclass,automodule
      - name: Doc check
        run: check/doctest -q
  nbformat:
    name: Notebook formatting
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Doc check
        run: check/nbformat
  pytest:
    name: Pytest Ubuntu
    strategy:
      matrix:
        python-version: ['3.7', '3.8']
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r dev_tools/conf/pip-list-dev-tools.txt
          pip install codeowners # linux only package
      - name: Pytest check
        run: check/pytest --ignore=cirq/contrib --benchmark-skip --actually-quiet
  build_docs:
    name: Build docs
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r rtd_docs/requirements.txt
      - name: Build docs
        run: dev_tools/docs/build-rtd-docs.sh
  build_protos:
    name: Build protos
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          python -m pip install -r dev_tools/conf/pip-list-dev-tools.txt
          wget https://github.com/bazelbuild/bazel/releases/download/0.26.0/bazel_0.26.0-linux-x86_64.deb
          sudo dpkg -i bazel_0.26.0-linux-x86_64.deb
      - name: Build protos
        run: check/build-changed-protos
  coverage:
    name: Coverage check
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r cirq/contrib/contrib-requirements.txt
          pip install -r dev_tools/conf/pip-list-dev-tools.txt
      - name: Coverage check
        run: check/pytest-and-incremental-coverage --actually-quiet
  windows:
    name: Pytest Windows
    strategy:
      matrix:
        python-version: [ '3.7', '3.8' ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r dev_tools/conf/pip-list-dev-tools.txt
      - name: Pytest Windows
        run: check/pytest --ignore=cirq/contrib --benchmark-skip --actually-quiet
        shell: bash
  macos:
    name: Pytest MacOS
    strategy:
      matrix:
        python-version: [ '3.7', '3.8' ]
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r dev_tools/conf/pip-list-dev-tools.txt
      - name: Pytest check
        run: check/pytest --ignore=cirq/contrib --benchmark-skip
  notebooks:
    name: Notebook Tests
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install requirements
        run: pip install pytest pytest-xdist requests virtualenv filelock
      - name: Notebook tests
        run: check/pytest -n auto -m slow dev_tools/notebook_test.py