# Summary: add a welcoming comment to first-time contributors' issues & PRs.
# This is written in a generic way so that we can use the same workflow
# in all our quantumlib repos.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

name: Welcome first interactions
run-name: Welcome ${{github.actor}}'s first interaction

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

# Declare default permissions as read-only.
permissions: read-all

jobs:
  welcome:
    name: Check for first interaction
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      issues: write
      pull-requests: write
    env:
      repo: ${{github.server_url}}/${{github.repository}}
      files: ${{github.server_url}}/${{github.repository}}/blob/${{github.ref_name}}
    steps:
      - name: Add a welcome comment if appropriate
        uses: actions/first-interaction@d94ed8e502bc16de558688b9dd9a26261ae78a66 # v1.3.0
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          issue-message: |
            Hello and welcome, ${{github.actor}} ðŸ‘‹!

            Thanks for filing your first issue with the ${{github.repository}}
            project! Here are some quick tips:

            - Please make sure to read our [community participation
            guidelines](${{env.files}}/CODE_OF_CONDUCT.md).

            - If this is a bug report, we'll probably need the following
            details in order to diagnose the issue. If they're not in the
            original issue description, please consider adding them now:

               - [ ] Environment you are using (MacOS, Windows, Colab, etc.)
               - [ ] Version of Python you are using
               - [ ] Steps to reproduce the issue

            - Please look through [existing issues](${{env.repo}}/issues) for
            any that look the same as this one. If you find a similar issue,
            consider closing this one; if you don't want to close this one, can
            you explain how this new one differs from the other one?
          pr-message: |
            Hello and welcome, ${{github.actor}} ðŸ‘‹!

            Thanks for making your first pull request to the
            ${{github.repository}} project! Here are some quick tips:

            - Please make sure to read the [contributing
            guide](${{env.files}}/CONTRIBUTING.md) and [community participation
            guidelines](${{env.files}}/CODE_OF_CONDUCT.md).

            - All contributors must sign the [Contributor License
            Agreement](https://cla.developers.google.com/about) (CLA). If
            [googlebot](https://github.com/googlebot) leaves a comment on this
            pull request, make sure you follow the instructions it provides.

            - If this pull request fixes a bug, please reference the relevant
            issue number in the [issue tracker](${{env.repo}}/issues).

            Please allow time for the project community to be able to read and
            evaluate your pull request. Thanks again!
